services:
  frontend:
    image: 127.0.0.1:5000/ecommerce-frontend
    ports:
      - "8080:80"
    volumes:
      - /config/www
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      retries: 3
      timeout: 5s
    networks:
      - default
    depends_on:
      - backend
  backend:
    image: 127.0.0.1:5000/ecommerce-backend
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      retries: 3
      timeout: 5s
    volumes:
      - storage-public:/app/storage/app/public/
    networks:
      - default
    depends_on:
      - pgsql
  nginx-backend:
    image: lscr.io/linuxserver/nginx:latest
    volumes:
      - ./nginx-backend/nginx.conf:/config/nginx/site-confs/default.conf
      - ./backend:/app
      - /config/www
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      retries: 3
      timeout: 5s
    ports:
      - "80:80"
    networks:
      - default
  db:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ecommerce", "-U", "postgres"]
      retries: 3
      timeout: 5s
    volumes:
      - pgdata:/var/lib/postgresql
    secrets:
      - pgsql_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgsql_password
    networks:
      - default
  redis:
    image: redis:8.6.3-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - default
  minio:
    image: "minio/minio:latest"
    ports:
      - target: 9001
        published: 9091
        protocol: tcp
        mode: host 
    command: ["server", "/data", "--console", ":9000", "--console-address", ":9001"]
    volumes:
      - minio-storage:/data
    env_file:
      - ./minio/.env

volumes:
  pgdata:
  storage-public:
  minio-storage:

networks:
  default:
    driver: overlay

secrets:
  pgsql_password:
    file: pgsql_password.txt